sudo: required
os: linux
jdk: openjdk8
services:
  - docker
install:
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install graphviz realpath
  - curl -fsSL get.nextflow.io | bash
  - mkdir -p ~/bin; cp nextflow ~/bin
script:
  # Functional tests
  - travis_wait 35 bash .travis/ReUMP-test_all.sh
  - bash .travis/ReUMP-test_aftermzmine.sh
