sudo: required
os: linux
jdk: openjdk8
services:
  - docker
language: python
python:
  - "3.5"
before_install:
  - pip3 install 'numpy==1.18.1' 'scipy==1.4.1' 'pandas==0.25.3' 'matplotlib<3.0.0,>=2.1.1' 'plotly==4.5.0' 'seaborn==0.9.1' 'scikit-learn==0.22.1' matplotlib_venn 'multiqc==1.8' 'statsmodels==0.11.0' 'fastcluster==1.1.26' 'pylint==2.4.4'
install:
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install graphviz realpath
  - curl -fsSL get.nextflow.io | bash
  - mkdir -p ~/bin; cp nextflow ~/bin
script:
  # Functional tests
  - (timeout 180s bash .travis/RUMP-test_all.sh; exit 0) # test data is from Metabolights MTBLS146 (https://bit.ly/3dcPv6i)
  - bash .travis/RUMP-test_aftermzmine.sh
  - bash .travis/unit-test.sh
