# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-rump-1.1.0
channels:
- conda-forge
- bioconda
- defaults
- r
- anaconda-cluster
- conda-cluster
dependencies:
# nf-core
# - conda-forge::markdown=3.1.1.*
- pip
- java-jdk
- conda-forge::pymdown-extensions=6.0
# Pipeline
- fastqc=0.11.8
- font-ttf-dejavu-sans-mono=2.37
- multiqc=1.9
- unzip=6.0
- r-rmarkdown=1.18
- r-optparse=1.6.6
- ncurses=6.1
- biopython=1.77
# conda-forge
- Python 3.7.3
- astroid==2.3.3
- certifi==2020.6.20
- chardet==3.0.4
- click==7.1.2
- coloredlogs==14.0
- colormath==3.0.0
- cycler==0.10.0
- decorator==4.4.2
- fastcluster==1.1.26
- future==0.18.2
- humanfriendly==8.2
- idna==2.10
- importlib-metadata==2.0.0
- isort==4.3.21
- Jinja2==2.11.2
- joblib==0.17.0
- kiwisolver==1.3.1
- lazy-object-proxy==1.4.3
- lzstring==1.0.4
- Markdown==3.3.3
- MarkupSafe==1.1.1
- matplotlib==2.2.5
- matplotlib-venn==0.11.6
- mccabe==0.6.1
# - multiqc==1.8
- networkx==2.5
- numpy==1.18.1
- pandas==0.25.3
- patsy==0.5.1
- plotly==4.5.0
- pycurl==7.43.0.2
- PyGObject==3.30.4
- pylint==2.4.4
- pyparsing==2.4.7
# - python-apt==0.8.5
- python-dateutil==2.8.1
- pytz==2020.4
- PyYAML==5.3.1
- requests==2.24.0
- retrying==1.3.3
- scikit-learn==0.22.1
- scipy==1.4.1
- seaborn==0.11.1
- simplejson==3.17.2
- six==1.15.0
- spectra==0.0.11
- statsmodels==0.11.0
- typed-ast==1.4.1
- urllib3==1.25.11
- wrapt==1.11.2
- xlrd==1.2.0
- zipp==3.4.0
- r-httr==1.4.1
- r-progress==1.2.2
- r-rjsonio==1.3_1.4
- r-testthat==3.0.2


- pip:
  - multiqc==1.9
#  - python-apt==0.8.5
  - markdown==3.1.1

